### ISSUE TITLE
Add ability to exit out of “Projects” menu

### ISSUE THREAD

**Issue by Adrian-Samoticha** [hamaluik/timecop#105]
I am using Time Cop on macOS. Clicking the “Project” button to the left of the “What are you doing?” prompt opens a dialog that lets you choose the project you are currently working on:

<img width="661" alt="Screenshot 2023-01-14 at 18 31 03" src="https://user-images.githubusercontent.com/86920182/212487088-6ff68987-fed9-40f8-b85e-6b14c90958a1.png">

However, it is not possible to close the dialog without choosing a project. Neither pressing the escape key nor clicking the dialog's barrier closes the dialog.

**Comment by 12people** [comment]
Hey @Adrian-Samoticha 
I don't have the time to look into this right now, though might in the future.

Since you're using this on a Mac, which means you're building from source, perhaps you can make the adjustment yourself. The "ProjectSelectField.dart" file should be the place you need to change.

Feel free to submit a pull request for this. :)

**Comment by Adrian-Samoticha** [comment]
> Hey @Adrian-Samoticha I don't have the time to look into this right now, though might in the future.
> 
> Since you're using this on a Mac, which means you're building from source, perhaps you can make the adjustment yourself. The "ProjectSelectField.dart" file should be the place you need to change.
> 
> Feel free to submit a pull request for this. :)

Done. :)

**Comment by 12people** [comment]
@Adrian-Samoticha 
Excellent, thanks a ton!
