### ISSUE TITLE
Feature Request: Default timer

### ISSUE THREAD

**Issue by fabianmuehlberger** [hamaluik/timecop#143]
Hi, 

Just came across this app and love it! 

What I am missing is a default time tracking feature. Often I just want to track work time and don't care about setting a project or description to just track my working hours. But at a certain point in the day, I start a specific timer related to a project or task. 

Unfortunately, I have no idea how to program mobile apps, I am not a front end guy... and cannot judge how much effort it is to implement the following. 
If I can assist with the development, I will try my best

It would be great if the following would be possible:

- When the go button is pressed, with no information provided, the default "work hours" tracker starts  
- The tracker is stopped when the stop button is pressed. 
- If a second timer with a project or information provided is started, the default tracker stays active. 
- If the default tracker is stopped, all other trackers are stopped. 
- With no timer active, starting a tracker also starts the default tracker, 
- Stopping the last active tracker also stops the default tracker, if the default tracker was not started directly but was activated by a tracker. 

This would allow to easily track daily working hours if it is not relevant to assign a project or provide information. 

Best 
Fabian

**Comment by 12people** [comment]
Hey Fabian,
Thanks for interest in the app!
Are you using the mobile or the desktop version?

The config you're describing sounds like it would both be a lot of work as well as very niche for your use-case. However, I would say you can accomplish something similar with the current state of the app:
- Instead of using the "go" button to start the timer, just create a timer with the description "Work hours". Then, whenever you want to use that timer, just:
   - swipe on any entry with that description and tap "play" if in standard mode on mobile
   - tap "play" if showing project names on mobile
   - tap the play button that appears on hover if on Linux
- Use the stop button next to a running timer to stop just that running timer
- If you want to stop all running timers, use the "Stop all timers" entry in the timer menu

**Comment by fabianmuehlberger** [comment]
Hey @12people 
My current solution to the problem is to set it to 1 timer only and just sum up all entries in csv related to one day. When I do normal work, I just leave everything empty.
The sum per day is done by the report tab in the app, but when exporting I need to calculate it again. This works just fine. 
I thought it would be a nice feature to track the sum of all daily worked hours more easily, export the default timer, and have all hours tracked to report it to my employer. 

A more simple approach to my request would be to have a default timer that does the following:
- start with every other timer if no timer is activated. 
- stops with the last running timer. 
- create one default timer sum per day. 

No additional UI elements needed, not sure what has to be done in the backend, though.
