### ISSUE TITLE
Bring the app to F-Droid

### ISSUE THREAD

**Issue by 12people** [hamaluik/timecop#3]
I'd love to see this app on F-Droid, the most popular free and open-source app store for Android.

You could submit the app to F-droid via a [pull request](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) or simply create an issue on their Gitlab [Request for Packaging repository](https://gitlab.com/fdroid/rfp), asking for this app to be packaged.

Thank you for making this app!

**Comment by hamaluik** [comment]
I will try to do this as soon as I can get the time to figure out how to do so.

**Comment by opusforlife2** [comment]
You could open an RFP now and have the F-Droid maintainers help you out if something needs to be changed, like a non-free library that must be removed.

**Comment by opusforlife2** [comment]
BTW, I don't think this deserves its own issue, so I'll ask it here. Does this app offer similar functionality to Boosted on the Play Store?

**Comment by may-i-maybe-help-you** [comment]
I created a github account only to write this comment, because I was looking for a time tracking app which is privacy friendly for long time now.
Is there any way I can help you bringing it to F-Droid? I would love to donate you a coffee for the app on another way than Google Play Store. Please let me know how I may assist you with the F-Droid release :)

**Comment by hamaluik** [comment]
Sorry for the delay on this folks!

I would actually love some help with this. I spent some time trying to get `fdroidserver` to compile and run on my system, but ran into a wall of errors I was unable to get through. I haven't had time to deal with it since unfortunately as a lot has come up with work and home life lately that has just taken all my time away from me.

That said, I've now put it in the request for submission queue: https://gitlab.com/fdroid/rfp/-/issues/1324 where presumably you can voice your support for it. Probably the biggest help would be someone following [these instructions](https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/) to produce a pull request as I think that would be faster.

**Comment by may-i-maybe-help-you** [comment]
Hey @hamaluik 
Thanks for your effort! I can make a gitlab account as well to help you there, but it seems like that the guys from f-droid already responded to you: https://gitlab.com/fdroid/rfp/-/issues/1324

:) thanks again

**Comment by 12people** [comment]
@hamaluik Could you take another look at this? Sounds like you just need to implement a fastlane file structure now and specify which Flutter version you're using.

If you're busy, I could make a pull request.

**Comment by laurentS** [comment]
Hi everyone! I took the liberty to put together the absolute minimum fastlane file structure based on the help provided in https://gitlab.com/fdroid/rfp/-/issues/1324
I have zero experience with flutter (trying to build the app locally while I write this but getting dependency resolution problems) but maybe if we all chip in a couple of commits, we'll get there? In particular, I don't know how/where to specify the flutter version.

I've pushed my (tiny) contribution to https://github.com/hamaluik/timecop/pull/47 feel free to build upon it, I don't really have time to figure out all the dependency errors, but if someone knows flutter, you'll probably do it quickly...

**Comment by laurentS** [comment]
@hamaluik thanks for merging my PR!
The f-droid maintainer seems to suggest that you need to tag a new release so that they can produce a build, do you want to do that?
https://gitlab.com/fdroid/rfp/-/issues/1324#note_673825028

**Comment by opusforlife2** [comment]
@hamaluik Could you please tag a new version so that F-Droid can build it? It doesn't need to have all the latest commits, it could be identical to the current latest release. Or will that mess with your versioning scheme?

**Comment by 12people** [comment]
New version tagged!

**Comment by rugk** [comment]
Hmm your website https://timecop.app/de/ still only has Google play and Apple links? Would you mind to add an F-Droid badge there, too?

Full version:
https://github.com/hamaluik/timecop/issues/151
