### ISSUE TITLE
Can't import back a database exported from TimeCop - "Invalid database file!"

### ISSUE THREAD

**Issue by drawtheliner** [hamaluik/timecop#45]
1. Export database using TimeCop's Export function
2. Try to Import that back in. Get error.

Is this a known issue? How should I proceed?

**Comment by hamaluik** [comment]
Hmm, that's a problem. I'll look into it as soon as I have the time to do so.

**Comment by laurentS** [comment]
@drawtheliner I had the same issue, and looking at the code, I realised I was using the export function the wrong way.
You can export 2 different files:
- a CSV by doing "main menu / Export / (new export screen is shown with options) / set your options / tap blue button bottom right to get a CSV". This one cannot be imported back.
- a sqlite db file named `timecop.db` by doing "main menu / Export / tap the 'disks' icon top right / Export". You can then choose what to do with the file. I could import this one back into the app (I just used it to move to a new phone)

I think the issue is more about a confusing UI than in code. Maybe the "Import" & "Export" options top right should be made clearer, like "Import full database" and "Export full database"?

**Comment by drawtheliner** [comment]
Thanks! Good to know.
