### ISSUE TITLE
Generate screenshots using automated integration tests

### ISSUE THREAD

**Issue by 12people** [hamaluik/timecop#80]
Time Cop used to use the `screenshot` package for automated tests, but unfortunately, that package is obsolete and non-functional now.

Thankfully, Flutter 2.5 and above make it easy to take screenshots inside integration tests. It'd be useful if new tests were written to make generating screenshots easy again.

Here's a relevant article on this: https://dev.to/mjablecnik/take-screenshot-during-flutter-integration-tests-435k

And here's an example of a project using this in practice: https://github.com/wger-project/flutter/tree/feature/exercise-crowdsourcing/integration_test

**Comment by TomerPacific** [comment]
Hi @12people , can I help out with this issue?
What tests are you looking to add?

**Comment by 12people** [comment]
Well, mostly just looking to add a replacement for this file: https://github.com/hamaluik/timecop/blob/master/test_driver/screenshots_test.dart . This used to be an integration test used for automatically taking screenshots in a wide range of languages to use on app stores, but it used a specific package (`screenshot`), which no longer works and is no longer being developed.

You can use the aforementioned file as the outline for a rewritten new test. And it should now take screenshots using the Flutter binding's `takeScreenshot` method, as outlined in [this blog post](https://dev.to/mjablecnik/take-screenshot-during-flutter-integration-tests-435k).

Of course, if you'd also like to create other tests, feel free to. :)

**Comment by TomerPacific** [comment]
@12people, wanted to run the project before I start developing and got the following:

`Running "flutter pub get" in timecop...                         
Because every version of flutter_test from sdk depends on path 1.8.1 and timecop depends on path ^1.8.2, flutter_test from sdk is forbidden.
So, because timecop depends on flutter_test from sdk, version solving failed.
pub get failed (1; So, because timecop depends on flutter_test from sdk, version solving failed.)`

Flutter Doctor run:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.0.5, on Microsoft Windows [Version 10.0.19043.2130], locale he-IL)
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.3.6)
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the "Desktop development with C++" workload, and include these
      components:
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        C++ CMake tools for Windows
        Windows 10 SDK
[!] Android Studio (version 4.0)
    X Unable to determine bundled Java version.
[√] Android Studio (version 2021.2)
[√] IntelliJ IDEA Community Edition (version 2019.3)
[√] VS Code (version 1.72.2)
[√] Connected device (4 available)
[√] HTTP Host Availability

! Doctor found issues in 3 categories.
```

I use Android Studio for developing Flutter and not VS Code.
I have other Flutter projects that compile and run without any issues.

**Comment by 12people** [comment]
@TomerPacific

This seems to be a simple dependency conflict.

First, I would recommend that you upgrade Flutter to the latest version — 3.3.4, rather than the 3.0.5 that you're currently running. You can do that by running `flutter upgrade` in the Terminal.

If that doesn't solve the issue, you can just change the `path: ^1.8.2` line in this project's `pubspec.yaml` file to `path: ^1.8.1`.

Let me know if you have any more questions. :)

**Comment by TomerPacific** [comment]
@12people , thanks.

I didn't find any specific instructions on setting up things locally, just:

> After [installing and setting up Flutter](https://docs.flutter.dev/get-started/install) and downloading the Time Cop, you can simply [build and run](https://docs.flutter.dev/get-started/test-drive#run-the-app) this Flutter project, no extra steps needed.

So I didn't know what the required Flutter version is or if there is anything that needed to be done for dependencies.

**Upgrading Flutter to the latest stable version did the trick.**

Thanks

**Comment by TomerPacific** [comment]
@12people , I've started converting the `screenshots_test.dart` file. Below is an excerpt from the file:

```
Future<void> takeScreenshot(WidgetTester tester, IntegrationTestWidgetsFlutterBinding binding, String name) async {
  if (kIsWeb) {
    await binding.takeScreenshot(name);
  } else if (Platform.isAndroid) {
    await binding.convertFlutterSurfaceToImage();
    await tester.pumpAndSettle();
  }
  await binding.takeScreenshot(name);
}

void main() {

  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {

    testWidgets("take screenshots", (tester) async {
      await tester.pumpAndSettle();

      Finder startTimerButton = find.byType(StartTimerButton);

      // start by switching to the dark theme
      Finder menuButton = find.byKey(const ValueKey("menuButton"));
      await tester.tap(menuButton);

      Finder menuSettings = find.byKey(const ValueKey("menuSettings"));
      await tester.tap(menuSettings);

      Finder themeOption = find.byKey(const ValueKey("themeOption"));
      await tester.tap(themeOption);

      Finder themeDark = find.byKey(const ValueKey("themeDark"));

      await tester.tap(themeDark);
      await tester.pumpAndSettle();

      await takeScreenshot(tester, binding, "06 settings");
```

- I have incorporated the **takeScreenshot** solution referenced by the blog post
- Due to the fact the testing has changed in Flutter and methods have changed, I had to perform some adjustments
- When running this test in the terminal I am getting the following:

```
00:02 +0: end-to-end test take screenshots
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following assertion was thrown running a test:
The finder "zero widgets with key [<'menuButton'>] (ignoring offstage widgets)" (used in a call to
"tap()") could not find any matching widgets.

When the exception was thrown, this was the stack:
#0      WidgetController._getElementPoint (package:flutter_test/src/controller.dart:907:7)
#1      WidgetController.getCenter (package:flutter_test/src/controller.dart:846:12)
#2      WidgetController.tap (package:flutter_test/src/controller.dart:274:18)
#3      main.<anonymous closure>.<anonymous closure> (file:///C:/Users/Tomer/Documents/Projects/timecop/test_driver/integration_test/screenshot_test.dart:30:20)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  take screenshots
```
Meaning, it can't locate the menuButton widget.
I have tried loading the app (as can be seen in the example from the [documentation](https://docs.flutter.dev/cookbook/testing/integration/introduction)), but that leads to other errors that I believe are related to components in the application that are not initialized.

I have also looked at this [documentation](https://docs.flutter.dev/testing/integration-tests/migration), which explains how to migrate tests from flutter driver to integration _test.

I think right now, I am trying to understand what widget should be loaded in the pump method of the tester.

**Comment by 12people** [comment]
Hi @TomerPacific,

I'm not sure what exactly you mean by trying to load the app as in the example, but if you mean the `app.main();` part of the code is missing, that's exactly where the problem lies. In order to test the app, you have to run the app's code — there's no way around that. :)

Another bug that I noticed in your code is that you don't run `pumpAndSettle` when expecting UI changes as a result of e.g. taps or other actions. This is necessary to do because it takes some time for Flutter to draw the UI, and if the buttons and other interactive elements aren't there, you can't click on them in your test.

I took your code example and tweaked it so that it runs fine:
```
import 'package:flutter/widgets.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:timecop/main.dart' as app;
import 'package:timecop/screens/dashboard/components/StartTimerButton.dart';

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  group('end-to-end test', () {
    testWidgets('tap on the floating action button, verify counter',
        (tester) async {
      app.main();
      await tester.pumpAndSettle();

      Finder startTimerButton = find.byType(StartTimerButton);

      // start by switching to the dark theme
      Finder menuButton = find.byKey(const ValueKey("menuButton"));
      await tester.tap(menuButton);

      await tester.pumpAndSettle();

      Finder menuSettings = find.byKey(const ValueKey("menuSettings"));
      await tester.tap(menuSettings);

      await tester.pumpAndSettle();

      Finder themeOption = find.byKey(const ValueKey("themeOption"));
      await tester.tap(themeOption);

      await tester.pumpAndSettle();

      Finder themeDark = find.byKey(const ValueKey("themeDark"));

      await tester.tap(themeDark);
      await tester.pumpAndSettle();
    });
  });
}
```

Hope that helps. :)

**Comment by TomerPacific** [comment]
@12people ,

>  but if you mean the app.main(); part of the code is missing, that's exactly where the problem lies

That is **exactly** what I was referring to as I had code previously that invoked `app.main()`.

> Another bug that I noticed in your code is that you don't run pumpAndSettle when expecting UI changes as a result of e.g. taps or other actions.

I am aware of letting the test waiting for UI changes with pumpAndSettle, I just didn't get around to it since I saw that I had issues finding the desired widgets first.

Thanks for your quick reply.

**Comment by 12people** [comment]
Glad I could help.
So I'm hoping it works for you too now? I imagine the problem might have been with a missing `import 'package:timecop/main.dart' as app;` function, perhaps?

**Comment by TomerPacific** [comment]
@12people ,
Haven't tested it out yet, but I had the import there as well.
I'll post the results later today.

**Comment by 12people** [comment]
That's strange, not sure where the problem could be. I've never compiled on Windows, btw, only on Linux and macOS, so I'm not sure if there are extra complications in Windows.

Are you building the app for Android or for Windows? Windows is not a supported platform, so please run it inside an Android emulator.

Otherwise, I guess I would just try `flutter clean` and running `flutter test` again.

I was building my test for macOS, and there it worked for me. When building for Android, running `pumpAndSettle` didn't suffice when starting the app (maybe because Android 13 introduces a new splash screen and the test might have tried clicking on that screen rather than in the app itself). I added a `await Future<void>.delayed(const Duration(seconds: 2));` to fix it, and that did fix it, but that's honestly an ugly hack and I'm sure there's a better way to deal with this.

**Comment by 12people** [comment]
Also, just wondering — can you build and run the app itself?

**Comment by 12people** [comment]
About the `sqlite3` error — maybe you need to copy the `sqlite3.dll` file somewhere, as described here: https://pub.dev/packages/sqflite_common_ffi#windows

**Comment by TomerPacific** [comment]
Thank you for your continued assistance, @12people,.

> Are you building the app for Android or for Windows? Windows is not a supported platform, so please run it inside an Android emulator.

**I am building the application for Android, not Windows and running it inside an Android emulator.**

> Also, just wondering — can you build and run the app itself?

**Before working on the feature, I set up my local environment, which meant making sure the application compiles and runs.**

> I was building my test for macOS, and there it worked for me. When building for Android, running pumpAndSettle didn't suffice when starting the app (maybe because Android 13 introduces a new splash screen and the test might have tried clicking on that screen rather than in the app itself). I added a await Future<void>.delayed(const Duration(seconds: 2)); to fix it, and that did fix it, but that's honestly an ugly hack and I'm sure there's a better way to deal with this.

**The emulator I am using is configured for API 29, before the Splash change, so I am not sure the problem is derived from there. The sqlite3 error is what I was referring to in my previous comment:**

> "...that leads to other errors that I believe are related to components in the application that are not initialized."

> About the sqlite3 error — maybe you need to copy an sqlite3.dll file somewhere, as described here: https://pub.dev/packages/sqflite_common_ffi#windows

**I'll check it out and update you.**

**Are you running the test in a different manner than I am?**

**Comment by 12people** [comment]
Hm...

Well, my build environment is a bit different (running macOS on ARM, using VSCodium), but the test works for me both in an Android emulator and even when building the app for macOS.

The only file change on my side compared to what's in this repo is that I have this line under `dev_dependencies` in `pubspec.yaml`:
```
integration_test:
    sdk: flutter
```
But I assume you have that too.

The problem on your end seems to be package-related, but I don't know how to fix it. The only thing that came to mind was `flutter clean`, then running `flutter pub get` and then running the test or building the app. Maybe also try running `flutter doctor` to see if something is missing. Other than that, Stack Overflow is probably the best resource for dealing with the bug.

**Comment by 12people** [comment]
(Oh, and I can run the test without a problem both via the `flutter test` command as well as by running the test via VSCodium's UI.)

**Comment by TomerPacific** [comment]
@12people,
These are the things which I tried:

- Run `flutter clean` and `flutter pub get`
- Invalidate caches and restart Android Studio

I also have the integration_test dependency under dev_dependencies.

When searching for the sqlite3 error in SO, I found [this](https://stackoverflow.com/questions/62890116/missingpluginexceptionno-implementation-found-for-method-getdatabasespath-on-c), which doesn't add much to your proposed solution.

I'll keep digging around and update you if I have any breakthroughs.

**Comment by TomerPacific** [comment]
@12people,
happy to update that I have gone one step forward (with probably two steps back).
I moved the screenshot_test.dart file into a directory called integration_test that exists in the same root folder as lib and that solved the sqlite3 error and now when I run the test via terminal it starts.

Thing is, I see a black screen that says Test starting and then the test fails since it does not find the menuButton.

I tried adding a delay, but that did not work (in the video I cut the video short since I added a 20 second delay to see if it somehow helps).

![qemu-system-x86_64_d6AwcK2DYf](https://user-images.githubusercontent.com/23402988/197360488-1e92bb7e-9b9d-4fa1-b8b2-c5946aa19429.gif)

**Comment by 12people** [comment]
Oh, it didn't occur to me to ask about the folder structure. Yup, `integration_test` should be in the root folder.

Now it seems like your test environment is set up correctly and only the test itself needs to be fixed.

**Comment by 12people** [comment]
Did you add the line ```await Future<void>.delayed(const Duration(seconds: 20));``` before or after the first `pumpAndSettle` is run? For me, adding it between that and ```app.main();``` worked:

```
app.main();
await Future<void>.delayed(const Duration(seconds: 2));
await tester.pumpAndSettle();
```

It's an ugly hack, though, so it would be good to research how to do it correctly nevertheless.

**Comment by TomerPacific** [comment]
@12people, I added it a bit later and when I used your proposal, it works.
As you stated earlier, it is a hack and I'll google this and try to find an honest solution.

**Comment by TomerPacific** [comment]
@12people, researched around and tried various things to overcome having the Future.delayed code line there.
One proposal suggested to not use `app.main` and instead do this:

` await tester.pumpWidget(MyApp());`

Now, seeing as in the main.dart file of this application, MyApp is actually `TimeCopApp`, I have tried to use that.

Since the constructor expects a settings object of type **SettingsProvider**, I have tried to create it in various ways in order to do this, but am hitting a wall.

I am not so knowledgeable in Flutter and Bloc pattern.

Not saying that if I manage to overcome this, it will not require adding the Future.delayed code line.
I'm just chasing another angle to see if it might work.

[Source](https://stackoverflow.com/questions/65412897/new-integration-test-package-just-shows-test-starting-android)

**Comment by 12people** [comment]
I'm helping maintain this project, but I'm not the original developer, so I'm also unfortunately not very knowledgable about the Bloc pattern.

I discovered there's a MockSettingsProvider as well as a MockDataProvider file: https://github.com/hamaluik/timecop/blob/master/lib/data_providers/data/mock_data_provider.dart, https://github.com/hamaluik/timecop/blob/master/lib/data_providers/settings/mock_settings_provider.dart

Perhaps those could be of use to you here?

**Comment by TomerPacific** [comment]
@12people, that's one solution that I have tried, but to no avail...

**Comment by 12people** [comment]
Unfortunately, I don't think I can help with this :(

**Comment by hamaluik** [comment]
I'm not sure of the specifics here, but if you need a `SettingsProvider` in the test, you can instantiate a [`MockSettingsProvider`](https://github.com/hamaluik/timecop/blob/master/lib/data_providers/settings/mock_settings_provider.dart) which extends `SettingsProvider`.

Unfortunately I built this a long time ago when the bloc pattern was newer and I didn't fully know what I was doing, so the "Provider" nomenclature can be a bit ambiguous. You may actually need to instantiate a `MultiBlocProvider` as the application root (instead of `TimeCopApp`) so that all the relevant Blocs / providers / whatever can be injected into the `BuildContext` throughout the app during testing. Essentially, do what https://github.com/hamaluik/timecop/blob/master/lib/main.dart#L76-L98 does. I can't guarantee that will fix things, but I hopefully that will help.

**Comment by TomerPacific** [comment]
@12people , @hamaluik - good news. I have managed to make the test run without any hack using an instantiation of the MultiBlocProvier.

I am in the process of converting the old test into the new logic.

**Comment by hamaluik** [comment]
That key is coming from https://github.com/hamaluik/timecop/blob/master/lib/screens/dashboard/components/StoppedTimerRow.dart#L103

The idea in the screenshot end-to-end tests is to use the provider mocks so there is some data on the screen (without having to use an actual database), so the provider mock would have provided a timer with the id of '42', which the test could then locate the widget for using that interpolated key.

Now I don't see such a timer in the data provider mock, so I may be misremembering something or the code has changed since I looked at it last, but hopefully that should help you get going. You may need to change they key in the test, or update the mocks, etc, to get data that you can use.

**Comment by TomerPacific** [comment]
@hamaluik , @12people , I have opened a PR and will appreciate your feedback to understand if what I have done solves the required issue.

**Comment by 12people** [comment]
Hi @TomerPacific 

Thanks so much for the PR!
The test runs for me on Android, but it seems like no screenshots are actually generated.
I'm thinking a custom test driver might be missing. (When I run the test with a custom driver, it generates screenshots just fine.)
Is this file missing or am I running the test wrong / looking for screenshots in the wrong place?
